### ISSUE TITLE
Documentation on how to get started and change/ add widgets

### ISSUE THREAD

**Issue by SuperDJ** [ylacaute/ez-Dashing#11]
I'm very interested in using this project however when I try to change or add a widget nothing happens. I have followed the instructions on how to run it with Docker which worked fine.  So the dashboard is running and now I need to change and add widgets. However when I change or add a widget nothing is changing in the dashboard. Because of this I wonder if you could add more documentation on getting started and on changing/ adding widgets.

**Comment by ylacaute** [comment]
I'm glad to hear you !
If you try to add/remove widgets from the configuration.json, you just have to :
- update the file (widgets section)
- restart the mock api (npm run api) if you use the mocked API
- restart the spring boot server if you use the real server backend
- reload the browser

**Comment by ylacaute** [comment]
If you try to add a NEW widget (by code) here is the process :

- You first create your widget (you could copy past an existing widget directory, index + Widget and update files with your new widget name)
- Add it on the WidgetFactory (you will quickly understand what you have to do by reading the code)
- Update your dashboard.json configuration file (and follow the process described in my previous comment)

I have planned to write more documentation about all this, but I first need to finish the Widget/Datasources system to ease the process. I will probably do that in few weeks.

Please don't hesitate to ask me any questions, any feedback are welcome :)
