### ISSUE TITLE
Can a dashboard generate pages and access it?

### ISSUE THREAD

**Issue by basebase** [ylacaute/ez-Dashing#13]
Hello, I'm looking at your demo page, dashboard configuration can be saved and generate url access?

Thank

**Comment by ylacaute** [comment]
I am not sure to understand your question correctly. Currently, there is only one configuration file and one dashboard url, there is not way to "remember" a particular dashboard configuration by generating a specific url at at particular moment (this could be a feature). The dashboard url always gives the current server configuration.

**Comment by basebase** [comment]
OK, I understand what you mean.
Thank you
