### ISSUE TITLE
Sonar api change

### ISSUE THREAD

**Issue by Sabotaz** [ylacaute/ez-Dashing#15]
In the latest versions of sonar (I use Version 6.5), the metrics values are strings and not numbers anymore. In the Sonkins and sonar widgets, coverage, lines and violations need to be of type number, which is no more the case.
I tried to do a mapping like that (value is now a string):
```
{
  "baseUrl": "http://sonar.url",
  "refresh": 120,
  "mapping": {
    "int:lines": "$.component.measures[?(@.metric == 'lines')].value",
    "int:coverage": "$.component.measures[?(@.metric == 'coverage')].value",
    "int:violations": "$.component.measures[?(@.metric == 'violations')].value"
  },
  "queries": [
    {
      "id": "sonar-project",
      "path": "/api/measures/component?componentKey=package:project&metricKeys=coverage,lines,violations&format=json"
    }
  ]
}
```
but it doesn't seems to work, sonar values are not displayed.
I'll submit a possible fix for that, but I can't achieve to have sonar metrics displayed.

**Comment by Sabotaz** [comment]
see pull request #16

**Comment by ylacaute** [comment]
In the project, there is sample mock "sonar6.4.json", values are in string, but mapped as int and it works, so are you sure about the root cause problem ?

**Comment by Sabotaz** [comment]
It was a problem with the request path (in my case, it was doing request to http://sonar.url//sonar/api/measures/component?componentKey=package:project&metricKeys=coverage,lines,violations&format=json, who makes a contextpath conflict)

**Comment by ylacaute** [comment]
Ok great :) I fixed this double '/' problem. We can now defined paths in the dashboard.json with '/' or without '/' as first character.
