### ISSUE TITLE
"exec format error"

### ISSUE THREAD

**Issue by sunnythaper** [ylacaute/ez-Dashing#19]
Just installed Raspbian Lite on a Raspberry pi, then installed Docker using the convenience script as Docker recommends, and finally ran the ez-Dashing commands for demo and production and both times got the same error.

```
pi@design_tv:~$ sudo docker run -itp 8080:8080 --name ez-dashing --restart always -v /home/pi/Config/ez-config:/ez-config  ylacaute/ez-dashing:1.0.0
Unable to find image 'ylacaute/ez-dashing:1.0.0' locally
1.0.0: Pulling from ylacaute/ez-dashing
b56ae66c2937: Pull complete
fb0a3ca3d558: Pull complete
f7683d719f3b: Pull complete
d3162cf197b7: Pull complete
bfac0cdda62a: Pull complete
Digest: sha256:42aee6b0fba99e16d88880cfa512989b587a0e7391918bbc75badf82cfa10b3c
Status: Downloaded newer image for ylacaute/ez-dashing:1.0.0
standard_init_linux.go:195: exec user process caused "exec format error"
```

**Comment by ylacaute** [comment]
Can you try with ez-dashing:latest ? Do you have the same result ?

**Comment by sunnythaper** [comment]
Yep, unfortunately same result.

**Comment by ylacaute** [comment]
Do you know the version of the ARM architecture of your Raspberry pi ?

**Comment by ylacaute** [comment]
You could try to change the project Dockerfile parent to armv7/armhf-java

**Comment by sunnythaper** [comment]
I will try that tonight and see how it goes, thank you. In the meantime I ended up finding a node-red palette that provides dashboard functionality for my immediate needs.
