### ISSUE TITLE
How to make a dashboard editor with ez-Dashing.

### ISSUE THREAD

**Issue by sabiao** [ylacaute/ez-Dashing#22]
还是用中文把 : )，
我想做一个大屏展示页面，页面上可以放置很多组件（表格，地图，报表，饼形图，折线图...），用户可以自己编辑这个页面的展示内容。通过一个编辑器（有组件列表面板，画布，设置组件属性面板），从组件列表中选择组件拖动到画布调整布局，设置组件属性和数据绑定，然后保存到server，每个用户可以看到自己的页面展现方式

such as this editor:
![edit](https://user-images.githubusercontent.com/18094462/56102389-6571cf00-5f5f-11e9-88d6-1dbaa0c61aba.png)

现在把ez-dashing拉到本地，不太清楚如何借助ez做出一个dashboard编辑器
![huabu](https://user-images.githubusercontent.com/18094462/56102396-7589ae80-5f5f-11e9-817e-d2ecb7feed9f.png)

@ylacaute  thx~

**Comment by ylacaute** [comment]
What you want to do is technicaly possible by adding some code to ez-dashing, the project already give an example of saving the config from client to server.
You will also maybe have to change the grid system properties in order to move components exactly where the user want. You will also may want to increase the number of columns and lines.

**Comment by sabiao** [comment]
thanks @ylacaute  so much,  你是否有遇到大概可以满足这个需求的 工程或者插件 ，我拉下来ez后也看到了保存数据到server端的接口和数据格式，要向现有ez工程里添加组件列表面板和组件属性面板相关的代码，改动还是挺大的 ,haha...

**Comment by ylacaute** [comment]
哈哈没有，没有这样的插件......你必须自己开发它。也许，如果你付给我足够的钱我可以做到：D

**Comment by sabiao** [comment]
oh, 大概付需要多少，还有 你需要多长时间 (^_^)v
你的中文很6啊 👍

**Comment by ylacaute** [comment]
我的中文由Google Trad自动翻译lol我邀请您说英语。关于我的建议，这并不严重，我想你很匆忙，反正你也没有足够的钱。

**Comment by sabiao** [comment]
well~ @ylacaute . Then, as you know ,I don't have enough money, could  you pls give some advice, lots thanks for u.
Also , I am curious about your price, : )

**Comment by sabiao** [comment]
Hi @ylacaute ,can i ask another question? After started the service, I want to change the page widgets(add widget from widget list, or delete it from current page),Maybe I will create a variable point to config/dashboard.js,then i change it(push or pop), How can I dispatch this change to the current store. I saw you have load this config so early.
thank you very much!
